title: RailValley
email: info@railvalley.org
description: >- # this means to ignore newlines until "baseurl:"
  RailValley Ã¨ un'associazione per la promozione dell'innovazione in ambito
  ferroviario.
baseurl: ""
url: "https://railvalley.org"
github_username: railvalley

theme: minima
show_excerpts: true

header_pages:
  - pages.md
  - blog.md
  - about.md
